[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps = 
    ; Forzar la librería TCP correcta para ESP32
    mathieucarbou/AsyncTCP @ 3.2.4   ; <-- 1. OJO
    
    ; librerías originales 
    mathieucarbou/ESPAsyncWebServer @ 3.3.23
    earlephilhower/ESP8266Audio @ ^1.9.7
    witnessmenow/UniversalTelegramBot @ ^1.3.0
    mathworks/ThingSpeak @ ^2.0.0
    bogde/HX711 @ ^0.7.5
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.7
